### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by FloSkuL** [5andr0/PogoLocationFeeder#186]
When I open LocationFeeder,i get this message in debug tab
[2016-08-03 21:03:02][WARN] Exception:
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at PogoLocationFeeder.GUI.Common.Output.PrintPokemon(SniperInfo sniperInfo, String server, String channel)
   at PogoLocationFeeder.Program.<feedToClients>d__11.MoveNext() in D:\games\PogoLocationFeeder\PogoLocationFeeder\Program.cs:line 137
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PogoLocationFeeder.Program.<relayMessageToClients>d__12.MoveNext() in D:\games\PogoLocationFeeder\PogoLocationFeeder\Program.cs:line 149
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PogoLocationFeeder.Program.<>c__DisplayClass15_0.<<pollDiscordFeed>b__0>d.MoveNext() in D:\games\PogoLocationFeeder\PogoLocationFeeder\Program.cs:line 243

**Comment by Ilses** [comment]
Are you on the latest master, or a release version? It sounds like you're using the GUI?

**Comment by ExcuseMi** [comment]
That code is already refactored.
