### ISSUE TITLE
Crash when run on Win10

### ISSUE THREAD

**Issue by fazzertron** [5andr0/PogoLocationFeeder#19]
```Unhandled Exception: Discord.Net.HttpException: The server responded with error 400 (BadRequest)
   at Discord.Net.Rest.RestSharpEngine.<Send>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Rest.RestClient.<Send>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Rest.RestClient.<Send>d__21`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.DiscordClient.<Login>d__79.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Discord.DiscordClient.<BeginConnect>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.DiscordClient.<BeginConnect>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.DiscordClient.<Connect>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PogoLocationFeeder.Program.<>c__DisplayClass12_0.<<Start>b__2>d.MoveNext() in D:\games\PogoLocationFeeder\PogoLocationFeeder\Program.cs:line 143
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.DiscordClient.ExecuteAndWait(Func`1 asyncAction)
   at PogoLocationFeeder.Program.Start() in D:\games\PogoLocationFeeder\PogoLocationFeeder\Program.cs:line 139
   at PogoLocationFeeder.Program.Main(String[] args) in D:\games\PogoLocationFeeder\PogoLocationFeeder\Program.cs:line 23```

**Comment by padmanek** [comment]
have same error, what was the issue?

**Comment by fazzertron** [comment]
Incorrect username for discord - they've changed to using email addresses, so use your email.

**Comment by padmanek** [comment]
@fazzertron works great now, thanks!
