### ISSUE TITLE
 WebSocket protocol is not supported on this platform (0.1.5 GUI)

### ISSUE THREAD

**Issue by dody19852002** [5andr0/PogoLocationFeeder#229]
[2016-08-08 08:37:30][PKMN] PokemonGO 100IV CLUB:rare_coords_bot : Marowak at 40.76321,-73.977355 with unknown IV
[2016-08-08 08:37:32][WARN] Error
System.PlatformNotSupportedException: The WebSocket protocol is not supported on this platform.
   at System.Net.WebSockets.ClientWebSocket..ctor()
   at PogoLocationFeeder.Repository.PokeSpawnsRarePokemonRepository.<StartClient>d__7.MoveNext() in D:\games\PogoLocationFeeder\PogoLocationFeeder\Repository\PokeSpawnsRarePokemonRepository.cs:line 62

[2016-08-08 08:37:32][WARN] Error
System.PlatformNotSupportedException: The WebSocket protocol is not supported on this platform.
   at System.Net.WebSockets.ClientWebSocket..ctor()
   at PogoLocationFeeder.Repository.PokezzRarePokemonRepository.<StartClient>d__7.MoveNext() in D:\games\PogoLocationFeeder\PogoLocationFeeder\Repository\PokezzRarePokemonRepository.cs:line 62

[2016-08-08 08:37:33][PKMN] PokéGO- RARE SPOT & Chat!:90plus_ivonly: Dragonair at -33.873454,151.200454 with 95% IV

**Comment by tensei** [comment]
which windows are you on?

**Comment by dody19852002** [comment]
win 7 x86

**Comment by tensei** [comment]
not windows 7 compatible at the moment ,
in the process of rewriting, wait for update please

**Comment by 5andr0** [comment]
Sorry, i need some sleep. But when i wake up to a PR with a WebSocket4Net implementation or a smiliar compatible websocket i'd be happy to merge it

**Comment by ghcloudsigma** [comment]
yup same. Windows 7 x64 here

```
[2016-08-08 11:48:46][WARN] Error

System.PlatformNotSupportedException: The WebSocket protocol is not supported on this platform.
   at System.Net.WebSockets.ClientWebSocket..ctor()
   at PogoLocationFeeder.Repository.PokezzRarePokemonRepository.<StartClient>d__7.MoveNext() in D:\games\PogoLocationFeeder\PogoLocationFeeder\Repository\PokezzRarePokemonRepository.cs:line 62
[2016-08-08 11:48:46][WARN] Error

System.PlatformNotSupportedException: The WebSocket protocol is not supported on this platform.
   at System.Net.WebSockets.ClientWebSocket..ctor()
   at PogoLocationFeeder.Repository.PokeSpawnsRarePokemonRepository.<StartClient>d__7.MoveNext() in D:\games\PogoLocationFeeder\PogoLocationFeeder\Repository\PokeSpawnsRarePokemonRepository.cs:line 62
[2016-08-08 11:48:47][DEBUG] Pokewatchers API error: The remote server returned an error: (503) Server Unavailable.
```

pokewatcher, pokezz and pokespawn are not working. only pokesniper2 and discord that work.

**Comment by Zerotask** [comment]
Same here Win 7 32 bit

**Comment by Energex22** [comment]
Why do a release when over 1/2 the people still use a os you didn't support in the release... maybe next time make a quick note like "xxxxxx only works on xxxx until next update", i mean come on... i understand u are doing this for free, with donations... but come on..

**Comment by ExcuseMi** [comment]
Could some windows 7 users test the following builds?
[PogoLocationFeeder.GUI.exe.zip](https://github.com/5andr0/PogoLocationFeeder/files/406704/PogoLocationFeeder.GUI.exe.zip)
[PogoLocationFeeder.zip](https://github.com/5andr0/PogoLocationFeeder/files/406705/PogoLocationFeeder.zip)

@Energex22 If we knew it wouldn't work on windows 7, we wouldn't have released. It seems like none of the 4 devs working on this project are using windows 7.

**Comment by Zerotask** [comment]
@ExcuseMi  Before I tried the new file it didn't show up any error.
When I used that, after 5 seconds I got many error and a windows window popped out and says that the program isn't working.

![image](https://cloud.githubusercontent.com/assets/20150243/17478934/8fa3cfa2-5d6f-11e6-866b-6b1f9012eb6a.png)
("bei" means "at")

**Comment by ExcuseMi** [comment]
@Zerotask can i have the logs?

**Comment by Zerotask** [comment]
I already deleted them when downgrading to a working version. But I looked inside of it and there was nothing unusual, no errors or hints.

**Comment by demasque92** [comment]
![pogolocationfeeder](https://cloud.githubusercontent.com/assets/20906123/17483146/343533b6-5d85-11e6-8716-bec15ba3dae7.PNG)

**Comment by roytam1** [comment]
same here:
```
Newtonsoft.Json.JsonReaderException was unhandled
Message: An unhandled exception of type 'Newtonsoft.Json.JsonReaderException' occurred in Newtonsoft.Json
Additional information: Could not convert string to double: -75.4891330260181
Hide. Path 'lat', line 1, position 51.
```

**Comment by ExcuseMi** [comment]
Yey, you got past the previous error.
Now it seems like the data is not properly formatted. 
Will look into this later.

**Comment by Ghenghis** [comment]
Same here windows 7 x64

System.PlatformNotSupportedException: The WebSocket protocol is not supported on this platform.
   at System.Net.WebSockets.ClientWebSocket..ctor()
   at PogoLocationFeeder.Repository.PokezzRarePokemonRepository.<StartClient>d__7.MoveNext()
[14:13:11][PKMN] PokéGO- RARE SPOT & Chat!:rare_spotting: Magikarp at 41.88865,-87.626389 with 60% IV
[14:13:21][WARN] Error

System.PlatformNotSupportedException: The WebSocket protocol is not supported on this platform.
   at System.Net.WebSockets.ClientWebSocket..ctor()
   at PogoLocationFeeder.Repository.PokeSpawnsRarePokemonRepository.<StartClient>d__7.MoveNext()
[14:13:21][WARN] Error

System.PlatformNotSupportedException: The WebSocket protocol is not supported on this platform.
   at System.Net.WebSockets.ClientWebSocket..ctor()
   at PogoLocationFeeder.Repository.PokezzRarePokemonRepository.<StartClient>d__7.MoveNext()
[14:13:27][PKMN] Necrobot.io:sniping: Aerodactyl at 47.600792,-122.332179 with unknown IV
[14:14:01][WARN] Error

System.PlatformNotSupportedException: The WebSocket protocol is not supported on this platform.
   at System.Net.WebSockets.ClientWebSocket..ctor()
   at PogoLocationFeeder.Repository.PokezzRarePokemonRepository.<StartClient>d__7.MoveNext()
[14:14:01][WARN] Error

System.PlatformNotSupportedException: The WebSocket protocol is not supported on this platform.
   at System.Net.WebSockets.ClientWebSocket..ctor()
   at PogoLocationFeeder.Repository.PokeSpawnsRarePokemonRepository.<StartClient>d__7.MoveNext()

**Comment by saahilz** [comment]
how to put pokesniper2 folder path in location feeder, it crashes everytime i edit the config
any help
