### ISSUE TITLE
System.PlatformNotSupportedException: The WebSocket protocol

### ISSUE THREAD

**Issue by suwung** [5andr0/PogoLocationFeeder#243]
Hello,
i have some error like this, am using windows server 2008 r2 64. I am using CLI version. Please fix. Thank you
[WARN] Error

System.PlatformNotSupportedException: The WebSocket protocol is not supported on this platform.
   at System.Net.WebSockets.ClientWebSocket..ctor()
   at PogoLocationFeeder.Repository.PokeSpawnsRarePokemonRepository.<StartClient>d__7.MoveNext()
[2016-08-08 18:52:07][WARN] Error

System.PlatformNotSupportedException: The WebSocket protocol is not supported on this platform.
   at System.Net.WebSockets.ClientWebSocket..ctor()
   at PogoLocationFeeder.Repository.PokezzRarePokemonRepository.<StartClient>d__7.MoveNext()

**Comment by roytam1** [comment]
check this out: https://github.com/5andr0/PogoLocationFeeder/issues/229

**Comment by suwung** [comment]
@roytam1 ; thank you, it's working now

case close

**Comment by 2ez4mel** [comment]
how to fix ser?? :(
