### ISSUE TITLE
WebSockets Error

### ISSUE THREAD

**Issue by CalmerThanTheDude** [5andr0/PogoLocationFeeder#257]
I'm getting the following error in the Debug window:

```
[2016-08-08 12:32:35][WARN] Error
System.PlatformNotSupportedException: The WebSocket protocol is not supported on this platform.
   at System.Net.WebSockets.ClientWebSocket..ctor()
   at PogoLocationFeeder.Repository.PokezzRarePokemonRepository.<StartClient>d__7.MoveNext() in D:\games\PogoLocationFeeder\PogoLocationFeeder\Repository\PokezzRarePokemonRepository.cs:line 62
```

The funny thing is I don't use D:\games\PogoLocationFeeder that's not where I store PogoLocationFeeder it seems like it's a left over from someone else running the project there.

I get nothing from Discord channels, just pokesnipers.

**Comment by Adriskye** [comment]
me 2

**Comment by Ilses** [comment]
The websocket thing looks a lot like #229
