### ISSUE TITLE
servers

### ISSUE THREAD

**Issue by zenis12** [5andr0/PogoLocationFeeder#278]
was working good.. now only shows pokesnipers servers.. what happened? i didnt changed anything

**Comment by anti2canz** [comment]
same mine don't even show anything at all now, was working fine this morning.

**Comment by TickleFairy** [comment]
[2016-08-09 10:44:22][WARN] Error

System.PlatformNotSupportedException: The WebSocket protocol is not supported on this platform.
   at System.Net.WebSockets.ClientWebSocket..ctor()
   at PogoLocationFeeder.Repository.PokeSpawnsRarePokemonRepository.<StartClient>d__7.MoveNext()
[2016-08-09 10:44:22][DEBUG] Pokewatchers API error: The remote server returned an error: (503) Server Unavailable.
[2016-08-09 10:44:24][DEBUG] Pokewatchers API error: The remote server returned an error: (503) Server Unavailable.
[2016-08-09 10:44:25][DEBUG] Pokewatchers API error: The remote server returned an error: (503) Server Unavailable.
[2016-08-09 10:44:26][DEBUG] Pokewatchers API error: The remote server returned an error: (503) Server Unavailable.

**Comment by TickleFairy** [comment]
2016-08-09 10:45:22][DEBUG] No new pokemon on PokeZZ
[2016-08-09 10:45:32][DEBUG] Pokewatchers API error: The remote server returned an error: (503) Server Unavailable.
[2016-08-09 10:45:33][DEBUG] Pokewatchers API error: The remote server returned an error: (503) Server Unavailable.
[2016-08-09 10:45:35][DEBUG] Pokewatchers API error: The remote server returned an error: (503) Server Unavailable.
[2016-08-09 10:45:36][DEBUG] Pokewatchers API error: The remote server returned an error: (503) Server Unavailable.
[2016-08-09 10:45:42][WARN] Error

System.PlatformNotSupportedException: The WebSocket protocol is not supported on this platform.
   at System.Net.WebSockets.ClientWebSocket..ctor()
   at PogoLocationFeeder.Repository.PokeSpawnsRarePokemonRepository.<StartClient>d__7.MoveNext()
[2016-08-09 10:45:52][DEBUG] No new pokemon on PokeZZ
[2016-08-09 10:45:52][DEBUG] No new pokemon on PokeSpawns

**Comment by Alukardz** [comment]
I can't get anything from discord servers [2016-08-09 10:59:01][WARN] Experiencing connection issues. Throttling...

**Comment by TickleFairy** [comment]
I see that one as well.

**Comment by erc1IC** [comment]
maybe this

> Grabbing the list
> 
> https://pokewatchers.com/api.php?act=grab
> **You may only use this link every 5 seconds.**

**Comment by zenis12** [comment]
the program is working for me, but only shows the pokesniper server

**Comment by Alukardz** [comment]
@zenis12  you are not getting this [2016-08-09 11:54:59][WARN] Experiencing connection issues. Throttling...?

**Comment by Furak** [comment]
[2016-08-09 18:00:59][WARN] Error

System.PlatformNotSupportedException: The WebSocket protocol is not supported on this platform.
   at System.Net.WebSockets.ClientWebSocket..ctor()
   at PogoLocationFeeder.Repository.PokeSpawnsRarePokemonRepository.<StartClient>d__7.MoveNext()
[2016-08-09 18:00:59][WARN] Error

System.PlatformNotSupportedException: The WebSocket protocol is not supported on this platform.
   at System.Net.WebSockets.ClientWebSocket..ctor()
   at PogoLocationFeeder.Repository.PokezzRarePokemonRepository.<StartClient>d__7.MoveNext()
[2016-08-09 18:01:01][DEBUG] Pokewatchers API error: The remote server returned an error: (503) Server Unavailable.
[2016-08-09 18:01:02][DEBUG] Pokewatchers API error: The remote server returned an error: (503) Server Unavailable.
[2016-08-09 18:01:03][DEBUG] Pokewatchers API error: The remote server returned an error: (503) Server Unavailable.
[2016-08-09 18:01:04][DEBUG] Pokewatchers API error: The remote server returned an error: (503) Server Unavailable.
[2016-08-09 18:01:09][DEBUG] No new pokemon on PokeZZ
[2016-08-09 18:01:09][DEBUG] No new pokemon on PokeSpawns
[2016-08-09 18:01:17][WARN] Experiencing connection issues. Throttling...
[2016-08-09 18:01:24][DEBUG] Pokesnipers API error: The remote server returned an error: (502) Bad Gateway.

**Comment by zenis12** [comment]
[2016-08-09 17:52:27][PKMN] Pokesnipers: Exeggutor at 32.859113,-96.893791 with unknown IV until 17:54:18
[2016-08-09 17:52:55][WARN] Error
System.PlatformNotSupportedException: O protocolo WebSocket não tem suporte nesta plataforma.
   em System.Net.WebSockets.ClientWebSocket..ctor()
   em PogoLocationFeeder.Repository.PokeSpawnsRarePokemonRepository.<StartClient>d__7.MoveNext() na D:\games\PogoLocationFeeder\PogoLocationFeeder\Repository\PokeSpawnsRarePokemonRepository.cs:linha 62

[2016-08-09 17:52:56][WARN] Experiencing connection issues. Throttling...
[2016-08-09 17:53:14][PKMN] Pokesnipers: Rapidash at 39.916283,-75.144641 with unknown IV until 17:56:56
[2016-08-09 17:53:14][PKMN] Pokesnipers: Venusaur at -34.653236,-58.480172 with unknown IV until 18:00:01
[2016-08-09 17:53:35][WARN] Error
System.PlatformNotSupportedException: O protocolo WebSocket não tem suporte nesta plataforma.
   em System.Net.WebSockets.ClientWebSocket..ctor()
   em PogoLocationFeeder.Repository.PokeSpawnsRarePokemonRepository.<StartClient>d__7.MoveNext() na D:\games\PogoLocationFeeder\PogoLocationFeeder\Repository\PokeSpawnsRarePokemonRepository.cs:linha 62

**Comment by zenis12** [comment]
maybe it changed the server, cant see another reason

**Comment by TickleFairy** [comment]
Servers could be down.

**Comment by zenis12** [comment]
because it stopped working a couple hours ago.. only pokesnipers server working.... more people can confirm?
