### ISSUE TITLE
System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server

### ISSUE THREAD

**Issue by Aeohard** [5andr0/PogoLocationFeeder#282]
**Anyone can explain this problem? I experiencing this always and I receiving sniping pokemons only from Pokesnipers...**

> [2016-08-09 19:46:28][WARN] Error

System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 188.165.224.208:49006
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.ClientWebSocket.<ConnectAsyncCore>d__21.MoveNext()
   at System.Net.WebSockets.ClientWebSocket.<ConnectAsyncCore>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PogoLocationFeeder.Repository.PokeSpawnsRarePokemonRepository.<StartClient>d__7.MoveNext()

**Comment by TickleFairy** [comment]
Just resolved.

**Comment by hdrksbv** [comment]
still same, i think because poke sniper down ?

**Comment by TickleFairy** [comment]
[2016-08-09 13:30:30][DEBUG] Discord message received: 209077347503046656: Lapras 47.596018, -122.33293 IV 62%
[2016-08-09 13:30:30][DEBUG] Skipping duplicate SniperInfo: id: Lapras, Latitude: 47.596018, Longitude: -122.33293, IV: 62%
[2016-08-09 13:30:33][DEBUG] Discord message received: 209260366784495616: dragonite please
[2016-08-09 13:30:33][DEBUG] Can't get coords from line: dragonite please
[2016-08-09 13:30:38][DEBUG] No new pokemon on PokeZZ

**Comment by hdrksbv** [comment]
[2016-08-10 00:20:30][WARN] Error

System.PlatformNotSupportedException: The WebSocket protocol is not supported on this platform.
   at System.Net.WebSockets.ClientWebSocket..ctor()
   at PogoLocationFeeder.Repository.PokezzRarePokemonRepository.<StartClient>d__7.MoveNext()
[2016-08-10 00:20:30][WARN] Error

System.PlatformNotSupportedException: The WebSocket protocol is not supported on this platform.
   at System.Net.WebSockets.ClientWebSocket..ctor()
   at PogoLocationFeeder.Repository.PokeSpawnsRarePokemonRepository.<StartClient>d__7.MoveNext()

**Comment by TickleFairy** [comment]
Did you try restarting? as that looks 10 minutes old if not more?

**Comment by hdrksbv** [comment]
restarting the pogo feeder , or pc ?

**Comment by TickleFairy** [comment]
Feeder, the reason why is these are server side issues. The servers basically are not refreshing or allowing your connection.

**Comment by hdrksbv** [comment]
yeah im already restart the feeder a few time, but im still got the error

**Comment by hdrksbv** [comment]
because this  "UseWebsocket": false,
?

**Comment by kamui78** [comment]
i have same issue

**Comment by filo4u** [comment]
This problem has been solved at #263 
The last line tell you what website is not responding.
example: at PogoLocationFeeder.Repository.PokeSpawnsRarePokemonRepository.d__7.MoveNext()

This means pokespawns is down and you can disable it on the config file.

**Comment by Aeohard** [comment]
Thanks for that @filo4u... ;)
