### ISSUE TITLE
Unhandled error on start

### ISSUE THREAD

**Issue by t-p-l-k** [5andr0/PogoLocationFeeder#29]
At the beginning of execution I get the following error. Also, I don't have "D:\games\PogoLocationFeeder\" directory so probably it's some kind of a mistake in code.
I use Release v0.0.1
```
Listening...

Unhandled Exception: Discord.Net.TimeoutException: An operation has timed out.
   at Discord.Net.WebSockets.WebSocket.WaitForConnection(CancellationToken cancelToken)
   at Discord.Net.WebSockets.GatewaySocket.WaitForConnection(CancellationToken cancelToken)
   at Discord.DiscordClient.<BeginConnect>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.DiscordClient.<BeginConnect>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.DiscordClient.<Connect>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PogoLocationFeeder.Program.<>c__DisplayClass12_0.<<Start>b__2>d.MoveNext() in D:\games\PogoLocationFeeder\PogoLocationFeeder\Program.cs:line 143
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.DiscordClient.ExecuteAndWait(Func'1 asyncAction)
   at PogoLocationFeeder.Program.Start() in D:\games\PogoLocationFeeder\PogoLocationFeeder\Program.cs:line 139
   at PogoLocationFeeder.Program.Main(String[] args) in D:\games\PogoLocationFeeder\PogoLocationFeeder\Program.cs:line 23
```

**Comment by Nozk** [comment]
Same error

**Comment by Nozk** [comment]
Just received notification that his may be caused by discord having a rough time right now, try again later maybe?

**Comment by t-p-l-k** [comment]
https://status.discordapp.com/
Looks like it's discord server side problem.

**Comment by Ilses** [comment]
Yep, Discord is down. I don't think you're on the latest master -- Program.cs:143 is `};` on my end. Could you post the commit hash from `git log` so I can check up on our error handling?

**Comment by t-p-l-k** [comment]
@Ilses as said in the first post I was using pre-compiled Release v0.0.1. 
I guess here it is:
https://github.com/5andr0/PogoLocationFeeder/tree/v0.0.1

**Comment by Ilses** [comment]
Ok -- I pushed v0.0.2 recently -- could you check if this resolves your error?

**Comment by t-p-l-k** [comment]
@Ilses both v0.0.1 and v0.0.2 work right now. It was discord problem for sure.
